### ISSUE TITLE
Fails with Scalar-List-Util 1.27 and older

### ISSUE THREAD

**Issue by andk** [merrilymeredith/p5-Class-Type-Enum#1]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/61997314

Maybe bump the required version number. Cpantesters have pass reports from 1.35 and later.

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by merrilymeredith** [comment]
Hi @andk,  I understand this was an automatic sort of report, but maybe you can help me with this:

    List::Util: v1.33.0

[My dist should announce a requirement for List::Util 1.33 minimum][META.yml], yet these smokers still run tests on it.  I think I had this same problem with requiring a minimum version of Moo with another dist, there were some smokers that didn't pick up the requirement.

I know there is some historical weirdness with representing version values, but `"v1.33.0"` in my META.yml is the same form as the perl requirement, `"v5.12.0"`, and I don't seem to be having problems with older perl smokers trying to test my dist.

I checked another dist's META.yml though, and its version requirements are strings as well, but without the "v" prefix.  (Mine were generated by dzil's Prereqs and AutoPrereqs, incidentally.)

Any idea if that's all I need to do to fix this?

[META.yml]: http://cpansearch.perl.org/src/MHOWARD/Class-Type-Enum-0.003/META.yml

**Comment by andk** [comment]
>>>>> On Sat, 28 Nov 2015 12:27:58 -0800, Meredith Howard <notifications@github.com> said:

  > Hi @andk, I understand this was an automatic sort of report, but maybe you can
  > help me with this:

  > List::Util: v1.33.0

OK, I see this in your META.yml. I suppose your system had 1.33 of
List::Util installed when you produced this META.yml? I find the line

  our $VERSION    = "1.33";

in
https://metacpan.org/source/PEVANS/Scalar-List-Utils-1.33/lib/List/Util.pm#L19

So whoever translated this to v1.33.0 needs to receive a bugreport,
because "1.33" is not the same as "v1.33.0".

  > My dist should announce a requirement for List::Util 1.33 minimum, yet these
  > smokers still run tests on it. I think I had this same problem with requiring a
  > minimum version of Moo with another dist, there were some smokers that didn't
  > pick up the requirement.

I'd hesitate to blame the smokers, rather the coercion of 1.33 into v1.33.0

  > I know there is some historical weirdness with representing version values, but
  > "v1.33.0" in my META.yml is the same form as the perl requirement, "v5.12.0",
  > and I don't seem to be having problems with older perl smokers trying to test
  > my dist.

Weirdness it is indeed, the conversion is not very intuitive. But the
short story from man version

         $variable   version->parse($variable)
         ---------   -------------------------
         1.23        v1.230.0
         "1.23"      v1.230.0
         v1.23       v1.23.0
         "v1.23"     v1.23.0
         "1.2.3"     v1.2.3
         "v1.2.3"    v1.2.3

reveals, that *if* somebody would like to convert to a v-string, it
would have to acknowledge

 1.33  ≙ v1.330.0
 1.033 ≙ v1.33.0
 5.12  ≙ v5.120.0
 5.012 ≙ v5.12.0

Witness

% perl -E 'say $^V->stringify'
v5.20.2
% perl -E 'say $^V->numify'
5.020002

  > I checked another dist's META.yml though, and its version requirements are
  > strings as well, but without the "v" prefix. (Mine were generated by dzil's
  > Prereqs and AutoPrereqs, incidentally.)

Maybe the culprit lies there. Maybe you could file a bug report there

  > Any idea if that's all I need to do to fix this?

I'm not a dzil user, all my modules predate dzil, so I'm not sure where
to start.

-- 
andreas

**Comment by merrilymeredith** [comment]
Thanks for the direction; it looks like I just didn't quite understand how the version styles compare to one another.  I removed the 'v' to get a simple float and rebuilt, and that seems to have covered the issue.
